version: '3'

services:
  database:
    image: postgres
    restart: always
    env_file:
      - database.env
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - "15432:5432"
    volumes:
      - postgres-dev-database:/var/lib/postgresql/data
    networks:
      - 'postgres-cookbook-network'


  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "henrique.laki@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2020!"
    ports:
      - "16543:80"
    depends_on:
      - database
    networks:
      - 'postgres-cookbook-network'


volumes:
  postgres-dev-database:

networks:
  postgres-cookbook-network:
    driver: 'bridge'

